Structure the to-do list
kennedyowusu/to-do-application-webpack pull request #1
Opened 2022-12-07 21:55 UTC by kennedyowusu

### I implemented the following

2022-12-07 23:03 UTC, mckent05 requested changes
Hi @kennedyowusu,

# STATUS: CHANGES REQUIRED ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/206315516-ca699815-7a37-4e3e-8d62-07dfa19cbe2e.gif)


## Highlights
- All linter checks are passing ✔️ 
- Your PR is professional 👏  


## Required Changes ♻️
- I cannot run your project well locally, please check that you have properly configured your webpack file
<img width="957" alt="hrhrhr" src="https://user-images.githubusercontent.com/73607512/206315821-04631fb1-e2d0-47ff-a86d-54545e3afc09.PNG"> 
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 23:03 UTC, mckent05 commented on src/index.js
> +window.onload = renderUIData;
**OPTIONAL** - Good job on the work done so far 👏 . I suggest it is cleaner to attach or call your `renderUIData` function to an event listener like `DOMContentLoaded`. Please fix this 😄

2022-12-08 07:02 UTC, kennedyowusu commented on src/index.js
> +window.onload = renderUIData;
Thanks. I will do that

2022-12-08 07:35 UTC, kennedyowusu commented
Resolved the issue raised by @mckent05 Image of the solution is below: 


![todo-with-webpack](https://user-images.githubusercontent.com/32777408/206386299-afe2cd24-1d14-423c-87d5-c44313eb6641.png)


I configured the project to run on port:3000. I like to use that port for frontend-related works. 

![port3000](https://user-images.githubusercontent.com/32777408/206386663-d81dd4d6-2286-4e2a-87f7-dd409d1546d9.png)

2022-12-08 07:47 UTC, cynthiainga approved these changes
## STATUS APPROVED ✔️ ✔️ 

Hi @kennedyowusu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 07:48 UTC, merged